#!/usr/bin/env bash
# best school x 10

i=1
while ((i<21))
do
    echo $i
    ((i++))
    case $i in

        5)
	     echo "bad luck from China"
	     ;;
	10)
	     echo "bad luck from Japan"
             ;;
       	18)
             echo "bad luck from Italy"
       	     ;;
    esac
done
