#!/usr/bin/env bash
# best school x 10

i=1
h=1
echo "Hour: 0"
while ((i!=60))
do
    echo $i
    ((i++))
    if ((h > 12))
    then
	((h++))
    elif (( i == 60))
    then
	i=1
	echo -n "Hour: "
	echo $h
	((h++))
    fi
done
