#!/usr/bin/env bash
# script to create server .
cp /etc/hosts ~/hosts.new
printf '127.0.0.2 \t localhost\n' > ~/hosts.new
printf '8.8.8.8 \t facebook.com\n' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
